# application-prod.yml (배포 환경 전용)
spring:
  datasource:
    url: jdbc:p6spy:oracle:thin:@//dblab.dongduk.ac.kr:1521/orclpdb
    username: s250106
    password: 11755
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        show_sql: false

# CORS 설정
cors:
  allowed-origins: https://studeal.example.com,https://www.studeal.example.com

# 로깅 레벨 (배포 환경에서는 DEBUG 대신 INFO 사용)
logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.springframework.security: INFO
    p6spy: INFO
